Metallurgy is the bane of my existance
Midnight145/blightfall-configs pull request #22
Opened 2024-12-28 11:17 UTC by koolkrafter5

- **Make the new supplier quest for the Tools and Modifiers book repeatable. Make the location for the repeatable bonemeal quest say "The Planet" instead of the default "New".**
- **Add a very expensive way to craft mana pearls for the thaumomorphic botanist essence without needing Botania infrastructure.**
- **Add aspects for all of the blood magic slates. Add aspects to soul shards (2 spiritus, 1 praecantatio, 1 vitreus). Move the line that sets the tainted blood shard's aspects to EssentiaEverything.zs from Misc. Singletons.zs.**
- **Set all metal nuggets to 1 metallum.**
- **So many minor tweaks to quest text. Add a reminder to the quest "Teching Up" that Tinkers' tools need to be fully repaired in order for parts to be switched out. Change the quest text for the tainted villager to not discourage players from trying to cure them. Add a quest that disables the "In Danger of Mission Failure" quest after winning the game to make 100% completion easier. Make the bound blade quest visible with the quest for the magician's blood orb completed to better guide new players.**
- **Add a print statement to ExecutiveMandate2625b.zs.**
- **Change sulfur and saltpeter blocks to use oredicts instead of being hardcoded to use Metallurgy ones.**
- **Unify all of the copper, tin, bronze, steel, silver, mithril, platinum, and electrum into the Thermal variant (Tinkers' variant was used for steel). All recipes that yield an ingot, nugget, or dust give only the unified item. Legacy worlds that have metals from the other mods can still use them/convert them all to the unified type thanks to oredict support. Allow for all metal storage blocks to be crafted with oredict thanks to NoMoreRecipeConflict. Rename Thermal platinum and nickel items like mithril already was. Hide all of the extra types of ingots/nuggets/dusts from NEI.**

2025-01-12 18:43 UTC, Midnight145 requested changes

2025-01-12 18:43 UTC, Midnight145 commented on scripts/MetalsAreAnnoying2.zs
> +recipes.addShapeless(<Metallurgy:precious.block:2>, [platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngot
you readd the recipe for the metallurgy block here instead of thermal's

2025-01-12 18:43 UTC, Midnight145 commented on scripts/MetalsAreAnnoying2.zs
> +recipes.addShapeless(<Metallurgy:precious.block:4>, [electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngot
likewise, you readd metallurgy's electrum block recipe here

2025-01-12 18:43 UTC, Midnight145 commented on scripts/Misc. Singletons.zs
> +recipes.remove(<ThaumicTinkerer:kamiResource:3>);
aren't ichor nuggets used in the wand cap?

2025-01-12 18:43 UTC, Midnight145 commented on scripts/Misc. Singletons.zs
> +mods.tconstruct.Casting.addTableRecipe(<ThermalFoundation:material:12>, <liquid:iron.molten> * 576, <TConstruct:gearCast>, false, 20);
i assume all of these are used for something unobtainable like a power gen option?

2025-01-12 18:43 UTC, Midnight145 commented on scripts/MetalsAreAnnoying2.zs
> +recipes.addShapeless(<Metallurgy:precious.block:1>, [silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngo
missed this the first pass, metallurgy block is readded here and likely elsewhere as well

2025-01-12 18:43 UTC, Midnight145 commented on scripts/ExecutiveMandate2625b.zs
> +# Mining levels are all set to 0 in
super minor thing, missing config comment here but it'd be nice to have for clarity

2025-01-12 18:43 UTC, Midnight145 commented on scripts/Botania.zs
> +mods.botania.Lexicon.removePage("botania.entry.rafflowsia", 0);
why is this being removed?

2025-01-12 18:43 UTC, Midnight145 commented on scripts/Botania.zs
> +mods.botania.Lexicon.removeEntry("botania.entry.primusLoci");
not familiar with primusLoci, what is it?

2025-01-12 18:43 UTC, Midnight145 commented on config/cofh/thermalfoundation/common.cfg
> +    B:ShowDisabledEquipment=true
is this also hidden in a different config file instead of here?

2025-01-12 18:43 UTC, Midnight145 commented on config/NEI/hiddenhandlers.cfg
> +tonius.neiintegration.mods.harvestcraft.RecipeHandlerChurn
what are these?

2025-01-12 18:43 UTC, Midnight145 commented on config/hqm/quests.hqm
can you compile a list of everything changed here (specifically quest text, I see there's a list in the PR) so i can review it?

2025-01-12 23:16 UTC, koolkrafter5 commented on scripts/MetalsAreAnnoying2.zs
> +recipes.addShapeless(<Metallurgy:precious.block:2>, [platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngotDict, platinumIngot
I want to have both be available for decorative purposes, since we have the no recipe conflict mod now. This new recipe allows oredict instead of only taking the metallurgy ingots in the default recipe.

2025-01-12 23:16 UTC, koolkrafter5 commented on scripts/MetalsAreAnnoying2.zs
> +recipes.addShapeless(<Metallurgy:precious.block:4>, [electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngotDict, electrumIngot
I want to have both be available for decorative purposes, since we have the no recipe conflict mod now. This new recipe allows oredict instead of only taking the metallurgy ingots in the default recipe.

2025-01-12 23:16 UTC, koolkrafter5 commented on scripts/Misc. Singletons.zs
> +recipes.remove(<ThaumicTinkerer:kamiResource:3>);
Nope. The recipe is 2 thaumium caps, an ichor ingot, and 4 ichor blood items.

2025-01-12 23:17 UTC, koolkrafter5 commented on scripts/Misc. Singletons.zs
> +mods.tconstruct.Casting.addTableRecipe(<ThermalFoundation:material:12>, <liquid:iron.molten> * 576, <TConstruct:gearCast>, false, 20);
They are used with the AE2 crank and grindstone which are disabled.

2025-01-12 23:17 UTC, koolkrafter5 commented on scripts/MetalsAreAnnoying2.zs
> +recipes.addShapeless(<Metallurgy:precious.block:1>, [silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngotDict, silverIngo
I want to have both be available for decorative purposes, since we have the no recipe conflict mod now. This new recipe allows oredict instead of only taking the metallurgy ingots in the default recipe.

2025-01-12 23:18 UTC, koolkrafter5 commented on scripts/Botania.zs
> +mods.botania.Lexicon.removePage("botania.entry.rafflowsia", 0);
Those pages are just for lore about how passive flowers decay, which we have disabled. There are other pages after those which explain how it works and are not removed.

2025-01-12 23:19 UTC, koolkrafter5 commented on scripts/Botania.zs
> +mods.botania.Lexicon.removeEntry("botania.entry.primusLoci");
Worldgen versions of dayblooms/nightshades which are new and not present on the BF map.

2025-01-12 23:20 UTC, koolkrafter5 commented on config/cofh/thermalfoundation/common.cfg
> +    B:ShowDisabledEquipment=true
Yeah, the disabled ones are hidden in the NEI configs now.

2025-01-12 23:26 UTC, koolkrafter5 commented on config/NEI/hiddenhandlers.cfg
> +tonius.neiintegration.mods.harvestcraft.RecipeHandlerChurn
A "handler" is what NEI calls the different tabs at the top when you look for recipes of an item, like a crafting table, furnace, etc. Hiding them stops them from showing up when you look for recipes of an item that uses them.
extracells.integration.nei.UniversalTerminalRecipe is the handler for the recipe of the (deprecated) Extra Cells universal terminal. Since it's not a regular crafting table recipe, I wasn't able to remove it with MT so I hid it this way.
tonius.neiintegration.mods.harvestcraft.RecipeHandlerQuern is a harvestcraft block called the Quern. It turns various items like wheat, rice, and potatoes into flour. The block was disabled previously, but I think the recent NEI update now has support for this handler so it shows all of those recipes when you search for flour.
tonius.neiintegration.mods.harvestcraft.RecipeHandlerChurn is a harvestcraft block called the Churn. It turns fresh milk and salt into butter. It's like the Quern where it was disabled previously, but NEI now shows the recipes for this handler when you search for recipes for cheese.

2025-01-12 23:28 UTC, Midnight145 commented on config/NEI/hiddenhandlers.cfg
> +tonius.neiintegration.mods.harvestcraft.RecipeHandlerChurn
Ahh, I was right about universal terminal handler, but had no clue what quern or churn handlers were referring to

2025-01-12 23:32 UTC, koolkrafter5 commented on scripts/ExecutiveMandate2625b.zs
> +# Mining levels are all set to 0 in
Oops, fixed in [729ab14](https://github.com/Midnight145/blightfall-configs/pull/22/commits/729ab1414df1c2a1338b6a15dc92494276bbad95).

2025-01-13 02:00 UTC, koolkrafter5 commented on config/hqm/quests.hqm
This should be most of what I changed. I also fixed various grammar issues that I saw but I have no idea which ones they were anymore.

### New Quests

Supplier
 - Tools and Modifiers: Repeatable quest for the Tools and Modifiers book from Caves to Kingdoms.

Dark One
- Elemental Summoning: Explains how to summon BM elementals for demonic blood shards.
- Even Further Beyond: Hidden quest for the crystal clusters needed for the T6 blood altar.
- Transcending the End: Transcendent blood orb quest, requires Even Further Beyond and The Endgame (archmage orb quest).
- Sigil of the Hardened Soul: Explains what it does. Requires Transcending the End and Bound Armor.
- Socketed Item Effects: Explains the socketing system for bound armor. Requires Bound Armor.
- Request Ethereal Slate: Upgrade a Demonic Slate to Ethereal for 10 TDO rep. Requires T5 orb quest.

### Changed Text

Instructor
- Tutorials, please!: Slightly changed the text explaining why you can't use vanilla tools. The Jaded was required by Mandate 2656b to install a neural implant that causes you to break them upon the attempt to use them.
- Teching Up: Added reminder that Tinkers' tools need to be fully repaired to swap parts.

Supplier
- Metal Requests: Changed the wording a little to be a bit less redundant.

Geologist
- Common Ores: Changed the wording from "materials" to "ores".
- Various ore quests: Capitalized the names of all of the ores in the quests for consistency.
- Various: Changed the text on the right side of many pages to better match the tasks and to give this quest page a bit of its own identity. "Please click "Manual Detect" while holding the following ore:", "Please deliver the following stones:", etc.

Scout
- Learning To Scout quests: All of the quest texts said to send "the dirt block underneath" the location in the biodome, but some of the tasks needed sand or hardened clay. This was fixed for consistency.

Paranormalist
- Various: Changed the text on the right side of many pages to give this quest page a bit of its own identity: "Please click "Manual detect" to allow me to study the following item(s):".

Colonist
- Ranching and Herding: Changed the text for this quest a bit. It now says that proving the planet is viable for ranching will improve crew morale.
- Restoring the World: Changed the text a bit. The text now asks you to print a "Scanner Merit Badge" (the actual name of the item) instead of one of the "Participation badges".

Xenobiologist
- Tainted Villager Autopsy: This quest now says "It would take a real miracle to save these poor souls" to leave open the possibility to cure them with silverleaf potions, the purity focus, or the dawn machine. It previously said that curing them would be impossible, which is not true. I believed the quest book until I accidentally cured one with a silverleaf potion because I believed the quest text when it said it was impossible.

Black Market
- Capitalized all metal names for consistency like in The Geologist.
- Changed the right page for the mithril quests to say "Note: This quest can accept either Mithril Block from Metallurgy or Thermal Foundation." It previously asked for mithril blocks from Metallurgy or mana-infused blocks from Thermal, but all mana-infused stuff was renamed to mithril so that was outdated.
- Changed the infuscolium/deep iron/dark steel quest texts a little. Now FutureForge Tech wants to strike a deal with the Miners' Guild to outfit their mining fleet using the metal you supply.

Various
- Capitalized mentions of Executive Mandate 2625b to be more consistent.
- Capitalized mentions of Homeworld for consistency.

### Changed Rewards

Instructor
- I Need No Tutorials!: Changed reputation reward to match the other branch. Changed the book reward to the correct one.

Engineer
- Now gives a Thermal bronze ingot instead of Metallurgy.

Black Market
- Mithril quests now give the Davinci's Vessels items instead of Archimedes' Ships.

### Changed Linking/Visibility

Supplier
- All energy cell refill quests are unlocked after the Request Leadstone Cell quest for better visibility. The trigger quests used to unlock the higher tier ones were removed.

Dark One
- Seeing the Unseen quest (Divination Sigil) is no longer a requirement for other quests.
- Moved the slate requests to a better spot on the page.
- The Bound Blade is now visible when the T3 orb quest is completed to better guide new players.

### Changed Tasks

Instructor
- A Little Help Here? (free bone meal quest): Increased the radius a bit to allow the quest to refresh on the outer edges of the map (but not while aboard The Jaded).

Engineer
- An ME Network: Now also requires an Energy Acceptor because that's needed to make the minimal working ME system.

2025-01-13 02:48 UTC, Midnight145 commented on config/hqm/quests.hqm
Cool, tysm. I'll merge for now and look over these as I have time

2025-01-13 02:48 UTC, Midnight145 approved these changes

2025-01-13 02:49 UTC, merged